name: Artifacts

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Pull CosmWasm optimizer image
        run: docker pull cosmwasm/workspace-optimizer:0.14.0

      - name: Compile contracts to wasm (optimizer)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/code" \
            --mount type=volume,source=optimizer_cache,target=/code/target \
            --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
            cosmwasm/workspace-optimizer:0.14.0

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/